[build]
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "github.com/DaviTostes/netlify-go"
  GO111MODULE = "on"
  GO_VERSION = "1.22"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200
